name: aws pe upload

on:
    push:
        branches:
        - main

jobs:
    upload-main-exe:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: AWS secret
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1

        - name: Upload-exe
          run: aws s3 cp ./main.exe s3://go-go-cli-v2/main.exe
